import javax.swing.*;
import java.awt.*;
import java.util.*;

public class EmployeeDashboard extends JFrame {
    private User employeeUser;
    private Employee employee;
    private java.util.List<Payroll> payrolls;

    public EmployeeDashboard(User user) {

        this.employeeUser = user;
        setTitle("Employee Dashboard");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(500, 400);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());

        // Load employee info first
        employee = findEmployee(user.getUsername());
        payrolls = loadPayrolls(employee.getId());

        // Top panel with logout
        JPanel topPanel = new JPanel(new BorderLayout());
        String welcomeText = (employee != null)
            ? ("Welcome, Employee: " + employee.getName())
            : ("Welcome, Employee: " + user.getUsername());
        JLabel welcome = new JLabel(welcomeText);
        JButton logoutBtn = new JButton("Logout");
        logoutBtn.addActionListener(e -> { dispose(); new LoginFrame(); });
        topPanel.add(welcome, BorderLayout.WEST);
        topPanel.add(logoutBtn, BorderLayout.EAST);
        add(topPanel, BorderLayout.NORTH);

        // Main tabbed pane
        JTabbedPane tabs = new JTabbedPane();

        // Payroll tab
        JPanel infoPanel = new JPanel(new GridLayout(0, 1));
        infoPanel.setBorder(BorderFactory.createTitledBorder("Payroll Details"));
        for (Payroll p : payrolls) {
            infoPanel.add(new JLabel("Month: " + p.getMonth()));
            infoPanel.add(new JLabel("Basic Salary: " + formatCurrency(p.getBasicSalary())));
            infoPanel.add(new JLabel("Deductions: " + formatCurrency(p.getDeductions())));
            infoPanel.add(new JLabel("Net Pay: " + formatCurrency(p.getNetPay())));
            infoPanel.add(new JLabel("Status: " + p.getStatus()));
            infoPanel.add(new JLabel("----------------------"));
        }
        tabs.addTab("Payroll", infoPanel);

        // Settings tab
        tabs.addTab("Settings", new EmployeeSettingsPanel(employeeUser));

        // Show flagged warning if employee is flagged (top box)
        if (employee != null && employee.isFlagged()) {
            JPanel flaggedPanel = new JPanel();
            flaggedPanel.setBackground(new Color(255, 220, 220));
            flaggedPanel.setBorder(BorderFactory.createLineBorder(Color.RED));
            flaggedPanel.add(new JLabel("You have been flagged. For more information, please contact management +639123456788."));
            JPanel flaggedBox = new JPanel(new BorderLayout());
            flaggedBox.add(flaggedPanel, BorderLayout.CENTER);
            add(flaggedBox, BorderLayout.NORTH);
        }

        add(tabs, BorderLayout.CENTER);
        setVisible(true);
    }

    private String formatCurrency(double amount) {
        return "₱" + String.format("%,.2f", amount);
    }

    private Employee findEmployee(String username) {
        java.util.List<String[]> data = CSVHandler.readCSV("data/employees.csv");
        if (data.isEmpty()) return null;

        String[] header = data.get(0);
        boolean newFormat = header.length >= 6
                && "id".equalsIgnoreCase(header[0])
                && "firstname".equalsIgnoreCase(header[1])
                && "lastname".equalsIgnoreCase(header[2]);

        for (int i = 1; i < data.size(); i++) {
            String[] row = data.get(i);
            // Username is the employee FIRST name (default generated by Admin)
            if (newFormat) {
                if (row.length < 5) continue;
                String firstName = String.valueOf(row[1]).trim();
                if (!username.equals(firstName)) continue;

                String lastName = (row.length >= 3) ? String.valueOf(row[2]).trim() : "";
                String position = (row.length >= 4) ? row[3] : "";
                double salary = (row.length >= 5) ? Double.parseDouble(row[4]) : 0.0;
                boolean flagged = false;
                if (row.length >= 6) {
                    flagged = "1".equals(String.valueOf(row[5])) || "true".equalsIgnoreCase(String.valueOf(row[5]));
                }
                return new Employee(row[0], firstName, lastName, position, salary, flagged);
            } else {
                if (row.length < 4) continue;
                String fullName = String.valueOf(row[1]);
                String firstName = fullName.trim().split("\\s+")[0];
                if (!username.equals(firstName)) continue;

                String[] parts = String.valueOf(row[1]).trim().split("\\s+");
                String lastName = (parts.length <= 1) ? "" : String.join(" ", java.util.Arrays.copyOfRange(parts, 1, parts.length));
                boolean flagged = false;
                if (row.length >= 5) {
                    flagged = "1".equals(String.valueOf(row[4])) || "true".equalsIgnoreCase(String.valueOf(row[4]));
                }
                return new Employee(row[0], firstName, lastName, row[2], Double.parseDouble(row[3]), flagged);
            }
        }
        return null;
    }

    private java.util.List<Payroll> loadPayrolls(String empId) {
        java.util.List<Payroll> list = new ArrayList<>();
        java.util.List<String[]> data = CSVHandler.readCSV("data/payroll.csv");
        for (int i = 1; i < data.size(); i++) {
            String[] r = data.get(i);
            if (r[1].equals(empId)) {
                list.add(new Payroll(r[0], r[1], r[2], Double.parseDouble(r[3]), Double.parseDouble(r[4]), Double.parseDouble(r[5]), r[6]));
            }
        }
        return list;
    }
}
